const CSRF_COOKIE = 'asterism_csrf';

export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly code: string,
    message: string,
  ) {
    super(message);
  }
}

export function readCookie(name: string): string | undefined {
  const prefix = `${encodeURIComponent(name)}=`;
  const item = document.cookie.split('; ').find((cookie) => cookie.startsWith(prefix));
  return item ? decodeURIComponent(item.slice(prefix.length)) : undefined;
}

const CSRF_MINT_PATH = '/api/v1/auth/csrf';

/**
 * Replaces a CSRF cookie the browser no longer has.
 *
 * Losing it used to be unrecoverable from the interface: every write answered
 * 403 and the token could only be reissued by logging in again — which was
 * itself a write.
 */
async function mintCsrfToken(): Promise<boolean> {
  const response = await fetch(CSRF_MINT_PATH, { method: 'POST', credentials: 'include' });
  return response.ok;
}

export async function apiRequest<T>(
  path: string,
  init: RequestInit = {},
  retry = true,
): Promise<T> {
  const method = (init.method ?? 'GET').toUpperCase();
  const headers = new Headers(init.headers);
  // FormData must set its own Content-Type: the boundary is generated by the
  // browser and a hand-written header would not carry it.
  const isFormData = typeof FormData !== 'undefined' && init.body instanceof FormData;
  if (init.body && !isFormData && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json');
  }
  const guarded = !['GET', 'HEAD', 'OPTIONS'].includes(method);
  if (guarded) {
    const csrf = readCookie(CSRF_COOKIE);
    if (csrf) headers.set('X-CSRF-Token', csrf);
  }
  const response = await fetch(path, { ...init, headers, credentials: 'include' });
  const body = (await response.json().catch(() => ({}))) as {
    error?: string;
    message?: string;
  };
  if (!response.ok) {
    // A rejected token is recoverable exactly once: mint a new one and replay.
    // `retry` stops a server that keeps refusing from looping, and the mint
    // call is excluded so its own failure cannot recurse into itself.
    if (
      response.status === 403 &&
      body.error === 'csrf_failed' &&
      guarded &&
      retry &&
      path !== CSRF_MINT_PATH &&
      (await mintCsrfToken())
    ) {
      return apiRequest<T>(path, init, false);
    }
    throw new ApiError(
      response.status,
      body.error ?? 'request_failed',
      body.message ?? `Request failed (${response.status})`,
    );
  }
  return body as T;
}

export const jsonBody = (value: unknown): Pick<RequestInit, 'body'> => ({
  body: JSON.stringify(value),
});

export const scopedKey = (organizationId: string | undefined, ...parts: unknown[]) => [
  'organization',
  organizationId ?? 'none',
  ...parts,
];
